# Drivers

In [2]:
import requests
import pandas as pd

In [3]:
# format is race number_language
# race 5 = canada
url = "https://fantasy.formula1.com/feeds/drivers/5_en.json"

r = requests.get(url)

print(r.status_code)

200

In [4]:
data = r.json()

print(type(data))
print(data.keys())

<class 'dict'>
dict_keys(['Data', 'Meta'])

In [5]:
print(type(data["Data"]))

<class 'dict'>

In [6]:
print(data["Data"].keys())

dict_keys(['Value', 'FeedTime'])

In [7]:
drivers = data["Data"]["Value"]

In [8]:
print(type(drivers))
print(len(drivers))
print(drivers[0])

<class 'list'>
33
{'PlayerId': '18', 'Skill': 1, 'PositionName': 'DRIVER', 'Value': 12.8, 'TeamId': '23', 'FUllName': 'Pierre Gasly', 'DisplayName': 'P. Gasly', 'TeamName': 'Alpine', 'Status': '0', 'IsActive': '1', 'DriverTLA': 'GAS', 'DriverReference': 'PIEGAS01', 'CountryName': 'Rouen, France', 'OverallPpints': '37.00', 'GamedayPoints': '0', 'SelectedPercentage': '19', 'CaptainSelectedPercentage': '1', 'OldPlayerValue': 13.0, 'BestRaceFinished': '6', 'HigestGridStart': '7', 'HigestChampFinish': '', 'FastestPitstopAward': '', 'BestRaceFinishCount': 1, 'HighestGridStartCount': 1, 'HighestChampFinishCount': 0, 'FastestPitstopAwardCount': 0, 'QualifyingPoints': '', 'RacePoints': '', 'SprintPoints': '', 'NoNegativePoints': '', 'F1PlayerId': '8', 'FirstName': 'Pierre', 'LastName': 'Gasly', 'SessionWisePoints': [{'sessionnumber': 1, 'sessiontype': 'Sprint Qualifying', 'points': None, 'nonegative_points': None}, {'sessionnumber': 2, 'sessiontype': 'Qualifying', 'points': None, 'nonegative_points': None}, {'sessionnumber': 3, 'sessiontype': 'Race', 'points': None, 'nonegative_points': None}], 'AdditionalStats': {'fastest_lap_pts': 0.0, 'dotd_pts': 0.0, 'overtaking_pts': 28.0, 'q3_finishes_pts': 10.0, 'top10_race_position_pts': 15.0, 'top8_sprint_position_pts': 1.0, 'total_position_pts': 26.0, 'total_position_gained_lost': 3.0, 'total_dnf_dq_pts': -20.0, 'value_for_money': 0.72}, 'old_Value': 0.0, 'new_value': 0.0, 'ProjectedGamedayPoints': '0', 'ProjectedNoNegativePoints': '0', 'ProjectedOverallPpints': '37.00'}

In [10]:
df = pd.json_normalize(drivers)

df.head()

,PlayerId,Skill,PositionName,Value,TeamId,FUllName,DisplayName,TeamName,Status,IsActive,...,AdditionalStats.fastest_lap_pts,AdditionalStats.dotd_pts,AdditionalStats.overtaking_pts,AdditionalStats.q3_finishes_pts,AdditionalStats.top10_race_position_pts,AdditionalStats.top8_sprint_position_pts,AdditionalStats.total_position_pts,AdditionalStats.total_position_gained_lost,AdditionalStats.total_dnf_dq_pts,AdditionalStats.value_for_money
0,18,1,DRIVER,12.8,23,Pierre Gasly,P. Gasly,Alpine,0,1,...,0.0,0.0,28.0,10.0,15.0,1.0,26.0,3.0,-20.0,0.72
1,11059,1,DRIVER,8.2,23,Franco Colapinto,F. Colapinto,Alpine,0,1,...,0.0,0.0,27.0,3.0,7.0,0.0,10.0,4.0,0.0,1.25
2,12,1,DRIVER,8.0,24,Fernando Alonso,F. Alonso,Aston Martin,0,1,...,0.0,0.0,32.0,0.0,0.0,0.0,0.0,11.0,-40.0,0.09
3,129,1,DRIVER,5.6,24,Lance Stroll,L. Stroll,Aston Martin,0,1,...,0.0,0.0,22.0,0.0,0.0,0.0,0.0,6.0,-65.0,-1.65
4,11051,1,DRIVER,5.2,2640,Gabriel Bortoleto,G. Bortoleto,Audi,0,1,...,0.0,0.0,27.0,3.0,2.0,0.0,5.0,7.0,-30.0,0.43

In [13]:
df.shape

(33, 49)

In [15]:
df.columns.tolist()

['PlayerId',
 'Skill',
 'PositionName',
 'Value',
 'TeamId',
 'FUllName',
 'DisplayName',
 'TeamName',
 'Status',
 'IsActive',
 'DriverTLA',
 'DriverReference',
 'CountryName',
 'OverallPpints',
 'GamedayPoints',
 'SelectedPercentage',
 'CaptainSelectedPercentage',
 'OldPlayerValue',
 'BestRaceFinished',
 'HigestGridStart',
 'HigestChampFinish',
 'FastestPitstopAward',
 'BestRaceFinishCount',
 'HighestGridStartCount',
 'HighestChampFinishCount',
 'FastestPitstopAwardCount',
 'QualifyingPoints',
 'RacePoints',
 'SprintPoints',
 'NoNegativePoints',
 'F1PlayerId',
 'FirstName',
 'LastName',
 'SessionWisePoints',
 'old_Value',
 'new_value',
 'ProjectedGamedayPoints',
 'ProjectedNoNegativePoints',
 'ProjectedOverallPpints',
 'AdditionalStats.fastest_lap_pts',
 'AdditionalStats.dotd_pts',
 'AdditionalStats.overtaking_pts',
 'AdditionalStats.q3_finishes_pts',
 'AdditionalStats.top10_race_position_pts',
 'AdditionalStats.top8_sprint_position_pts',
 'AdditionalStats.total_position_pts',
 'AdditionalStats.total_position_gained_lost',
 'AdditionalStats.total_dnf_dq_pts',
 'AdditionalStats.value_for_money']

In [15]:
df[df["PlayerId"] == "118"]

,PlayerId,Skill,PositionName,Value,TeamId,FUllName,DisplayName,TeamName,Status,IsActive,...,AdditionalStats.fastest_lap_pts,AdditionalStats.dotd_pts,AdditionalStats.overtaking_pts,AdditionalStats.q3_finishes_pts,AdditionalStats.top10_race_position_pts,AdditionalStats.top8_sprint_position_pts,AdditionalStats.total_position_pts,AdditionalStats.total_position_gained_lost,AdditionalStats.total_dnf_dq_pts,AdditionalStats.value_for_money
10,118,1,DRIVER,9.7,26,Esteban Ocon,E. Ocon,Haas F1 Team,0,1,...,0.0,0.0,44.0,0.0,1.0,0.0,1.0,11.0,0.0,1.44